---

- name: Install GUI Apps
  hosts: localhost

  tasks:
    - name: Install 1Password
      community.general.homebrew:
        name: 1Password
        state: latest
        install_options: cask
      ignore_errors: yes
    - name: Install IDEs, Terminal emulator and text editors
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
        install_options: cask,force
      with_items:
        - visual-studio-code
        - iterm2
        - notion
        - grammarly-desktop
        - drawio
        - setapp
      ignore_errors: yes
    - name: Install browsers
      community.general.homebrew:
        name: "{{ item }}"
        state: latest
        install_options: cask
      with_items:
        - firefox
        - google-chrome
        - brave-browser
        - opera
        - vivaldi
      ignore_errors: yes
...