---

- name: Install GUI Apps
  hosts: localhost

  tasks:
    - name: Install IDEs
      community.general.homebrew:
        name:
          - visual-studio-code
    - name: Install browsers
      community.general.homebrew:
        name:
          - firefox
          - chrome
          - brave-browser
          - opera
          - vivaldi
        state: latest

...