---

- name: Preparing the base environment
  hosts: localhost

  tasks:
    - name: install or update homebrew packages | common *nix tools
      community.general.homebrew:
        name:
          - coreutils
          - tree
          - jq
          - tmux
          - shellcheck
        state: latest
    - name: install or update homebrew packages | development tools (Git Related)
      community.general.homebrew:
        name:
          - git
          - gnupg
          - gh
          - tig
          - pre-commit
          - terraform-docs
          # - warrensbox/tap/tfswitch #! broken on m1 macs
        state: latest
    - name: install or update homebrew packages | networking tools
      community.general.homebrew:
        name:
          - nmap
          - ipcalc
          - iperf3
          - putty
          - openssh
          - wget
        state: latest
    - name: install or update homebrew packages | cloud CLIs
      community.general.homebrew:
        name:
          - oci-cli
          - awscli
          - azure-cli
          - google-cloud-sdk
        state: latest
...