---

- name: Preparing the base environment
  hosts: localhost

  tasks:
    # TODO - name: Install Docker Desktop cask
    # brew install --cask docker
    - name: install or update homebrew packages | development environments
      community.general.homebrew:
        name:
          - hyperkit
          - podman
          - minikube
          - kubectl
...